openapi: 3.2.0
info:
  title: Operations Hub Vis.pointclouds API
  version: 0.1.1
  description: ''
servers: []
tags:
- name: vis.pointclouds
paths:
  /api/vis/v1/pointclouds/{id}/{data_file}/:
    get:
      operationId: vis_api_get_pointcloud_data_file
      summary: Fetch data file associated with a given pointcloud ID
      parameters:
      - in: path
        name: id
        schema:
          title: Id
          type: integer
        required: true
      - in: path
        name: data_file
        schema:
          title: Data File
          type: string
        required: true
      responses:
        '200':
          description: OK
      description: Fetch data file associated with a given pointcloud ID.
      tags:
      - vis.pointclouds
      security:
      - APIKeyAuth: []
      - CookieAuth: []
components:
  securitySchemes:
    APIKeyAuth:
      type: http
      scheme: bearer
    CookieAuth:
      type: apiKey
      in: cookie
      name: opshub_prod_sessionid
    AuthBearer:
      type: http
      scheme: bearer
