openapi: 3.2.0
info:
  title: Operations Hub Docs API
  version: 0.1.1
  description: ''
servers: []
tags:
- name: Docs
paths:
  /api/graphql-schema:
    get:
      operationId: builderapi_urls_graphql_schema
      summary: GraphQL Schema (SDL)
      parameters: []
      responses:
        '200':
          description: OK
      description: Return the pre-generated GraphQL schema in SDL format.
      tags:
      - Docs
components:
  securitySchemes:
    APIKeyAuth:
      type: http
      scheme: bearer
    CookieAuth:
      type: apiKey
      in: cookie
      name: opshub_prod_sessionid
    AuthBearer:
      type: http
      scheme: bearer
